# Generated by Django 3.1.6 on 2021-11-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('Offer', models.BooleanField(default=False)),
            ],
        ),
    ]
